# Generated by Django 5.0.6 on 2026-07-27 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_notificationpreference_userachievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(db_index=True, max_length=2)),
                ('qtype', models.CharField(choices=[('grammar', 'Grammar (fill-in-the-blank)'), ('vocabulary', 'Vocabulary (meaning in context)'), ('reading', 'Reading comprehension')], max_length=12)),
                ('passage', models.TextField(blank=True, help_text='Reading questions only')),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'placement_questions',
                'ordering': ['level', 'qtype'],
            },
        ),
        migrations.CreateModel(
            name='PlacementSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=10)),
                ('current_level', models.CharField(default='A2', max_length=2)),
                ('rounds', models.JSONField(default=list)),
                ('asked_question_ids', models.JSONField(default=list)),
                ('suggested_level', models.CharField(blank=True, max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'placement_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
