# Generated by Django 5.0.6 on 2026-06-21 14:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "lessons",
                "ordering": ["unit", "order"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_fr", models.CharField(blank=True, max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_free", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "levels",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LessonComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("vocabulary", "Vocabulary"),
                            ("text", "Text"),
                            ("exercise", "Exercise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="content.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "lesson_components",
                "ordering": ["lesson", "order"],
            },
        ),
        migrations.CreateModel(
            name="TextBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(help_text="markdown / rich text")),
                (
                    "component",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_block",
                        to="content.lessoncomponent",
                    ),
                ),
            ],
            options={
                "db_table": "text_blocks",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="content.level",
                    ),
                ),
            ],
            options={
                "db_table": "units",
                "ordering": ["level", "order"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="content.unit",
            ),
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "duration",
                    models.PositiveIntegerField(default=0, help_text="seconds"),
                ),
                ("storage_key", models.CharField(max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[("processing", "Processing"), ("ready", "Ready")],
                        default="processing",
                        max_length=20,
                    ),
                ),
                (
                    "component",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video",
                        to="content.lessoncomponent",
                    ),
                ),
            ],
            options={
                "db_table": "videos",
            },
        ),
        migrations.CreateModel(
            name="VocabularyItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("word", models.CharField(max_length=255)),
                ("translation", models.CharField(max_length=255)),
                ("audio_url", models.URLField(blank=True)),
                ("example_sentence", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocabulary_items",
                        to="content.lessoncomponent",
                    ),
                ),
            ],
            options={
                "db_table": "vocabulary_items",
                "ordering": ["component", "order"],
            },
        ),
    ]
