# Generated by Django 5.0.6 on 2026-06-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabularyitem",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
