# Generated by Django 5.0.6 on 2026-07-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_vocabularyitem_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="script",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="vocabularyitem",
            name="difficulty",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="vocabularyitem",
            name="pronunciation_tip_ar",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vocabularyitem",
            name="syllables",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
