# Generated by Django 5.0.6 on 2026-07-27 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_strip_level_code_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(db_index=True, max_length=100, unique=True)),
                ('cefr_level', models.CharField(max_length=2)),
                ('translation_ar', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'word_levels',
                'ordering': ['word'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (pending review)'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=12),
        ),
        migrations.CreateModel(
            name='WordAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(db_index=True, max_length=255)),
                ('cefr_level', models.CharField(blank=True, max_length=2)),
                ('translation_ar', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('auto', 'Automatic (above lesson level)'), ('idiom', 'Idiom / fixed expression'), ('multi_meaning', 'Multi-meaning (context-specific)'), ('target_vocab', 'Lesson target vocabulary')], default='auto', max_length=20)),
                ('needs_review', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_annotations', to='content.lesson')),
            ],
            options={
                'db_table': 'word_annotations',
                'ordering': ['lesson', 'word'],
                'unique_together': {('lesson', 'word')},
            },
        ),
    ]
