# Generated by Django 5.0.6 on 2026-07-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_wordlevel_lesson_status_wordannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='import_ref',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('import_ref', ''), _negated=True), fields=('import_ref',), name='uniq_lesson_import_ref'),
        ),
    ]
