# Generated by Django 5.0.6 on 2026-06-21 14:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True / False"),
                            ("fill_blank", "Fill in the Blank"),
                            ("matching", "Matching"),
                            ("reorder", "Reorder"),
                            ("listening", "Listening"),
                            ("pronunciation", "Pronunciation"),
                            ("final_test", "Final Test"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "content_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Describes the accepted shape of Exercise.content",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "exercise_templates",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.JSONField(help_text="Actual content, matching the template"),
                ),
                ("points", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="content.lessoncomponent",
                    ),
                ),
            ],
            options={
                "db_table": "exercises",
                "ordering": ["component", "order"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("answer", models.JSONField()),
                ("is_correct", models.BooleanField(default=False)),
                ("score", models.IntegerField(default=0)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exercises.exercise",
                    ),
                ),
            ],
            options={
                "db_table": "exercise_attempts",
                "ordering": ["-attempted_at"],
            },
        ),
    ]
