# Generated by Django 5.0.6 on 2026-07-03 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisetemplate",
            name="code",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("true_false", "True / False"),
                    ("fill_blank", "Fill in the Blank"),
                    ("matching", "Matching"),
                    ("reorder", "Reorder"),
                    ("listening", "Listening"),
                    ("pronunciation", "Pronunciation"),
                    ("dictation", "Dictation"),
                    ("final_test", "Final Test"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="PronunciationAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("spoken_text", models.TextField(blank=True)),
                ("target_text", models.TextField(blank=True)),
                ("score", models.FloatField(default=0)),
                ("passed", models.BooleanField(default=False)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pronunciation_attempts",
                        to="exercises.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pronunciation_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pronunciation_attempts",
                "ordering": ["-created_at"],
            },
        ),
    ]
