# Generated by Django 5.0.6 on 2026-07-27 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(help_text='positive = earned, negative = spent')),
                ('type', models.CharField(choices=[('earned_article', 'Earned (article question)'), ('earned_bonus', 'Earned (completion bonus)'), ('spent_premium', 'Spent (premium redemption)')], max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='article_id / premium_grant_id the transaction refers to', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coin_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('source', models.CharField(choices=[('coins', 'Coins redemption'), ('subscription_monthly', 'Monthly subscription'), ('subscription_annual', 'Annual subscription'), ('manual_admin', 'Manual (admin)')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'premium_grants',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('google_play', 'Google Play Billing'), ('stripe', 'Stripe'), ('cmi', 'CMI')], max_length=20)),
                ('plan_code', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('external_id', models.CharField(max_length=512, unique=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.premiumgrant')),
            ],
            options={
                'db_table': 'payment_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
