# Generated by Django 5.0.6 on 2026-07-09 18:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_en", models.CharField(max_length=255)),
                ("title_ar", models.CharField(blank=True, max_length=255)),
                (
                    "content_short",
                    models.TextField(help_text="~50-word summary shown in-app"),
                ),
                ("source", models.CharField(blank=True, max_length=100)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("difficulty", models.CharField(default="B1", max_length=10)),
                ("country", models.CharField(default="ma", max_length=2)),
                (
                    "published_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "news_articles",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="NewsExercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("template", models.CharField(max_length=50)),
                ("content", models.JSONField(default=dict)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="news.newsarticle",
                    ),
                ),
            ],
            options={
                "db_table": "news_exercises",
                "ordering": ["order"],
            },
        ),
    ]
