# Generated by Django 5.0.6 on 2026-07-27 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'news_categories',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='content_type',
            field=models.CharField(choices=[('news', 'News (rewritten)'), ('story', 'Story (original)')], default='news', max_length=10),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_global',
            field=models.BooleanField(default=True, help_text="Visible regardless of the reader's country"),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (pending review)'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=12),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content_short',
            field=models.TextField(help_text='~50-word summary shown in lists'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='difficulty',
            field=models.CharField(default='B1', help_text='CEFR level', max_length=10),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category'),
        ),
        migrations.CreateModel(
            name='ArticleCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('all_correct', models.BooleanField(default=False)),
                ('bonus_awarded', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='news.newsarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'news_article_completions',
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='NewsQuestionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('coins_awarded', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='news.newsexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'news_question_results',
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
