# Generated by Django 5.0.6 on 2026-07-27 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0005_wordlevel_lesson_status_wordannotation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITutorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10)),
                ('system_prompt', models.TextField(blank=True)),
                ('turns', models.JSONField(default=list)),
                ('target_vocabulary', models.JSONField(default=list)),
                ('terms_used', models.PositiveIntegerField(default=0)),
                ('terms_total', models.PositiveIntegerField(default=0)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_sessions', to='content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_tutor_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITutorUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_tutor_usage',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
