"""Seed data for the independent placement question bank (v2 §1.2).

65 questions, 13 per level A1-C1, mixing grammar (fill-in-the-blank),
vocabulary (meaning in context), and reading comprehension. Written fresh for
placement — none reuse content from the 180 lessons.
"""

# (level, qtype, passage, question, options, correct_index)
QUESTIONS = [
    # ----------------------------- A1 ----------------------------------- #
    ("A1", "grammar", "", "I ___ a student.", ["am", "is", "are"], 0),
    ("A1", "grammar", "", "She ___ from Egypt.", ["are", "is", "am"], 1),
    ("A1", "grammar", "", "They ___ football on Fridays.", ["plays", "play", "playing"], 1),
    ("A1", "grammar", "", "___ you like tea?", ["Do", "Does", "Is"], 0),
    ("A1", "grammar", "", "This is ___ apple.", ["a", "an", "the"], 1),
    ("A1", "grammar", "", "We ___ two brothers.", ["has", "have", "having"], 1),
    ("A1", "vocabulary", "", "You sleep in a ___.", ["kitchen", "bed", "car"], 1),
    ("A1", "vocabulary", "", "The opposite of 'hot' is ___.", ["warm", "cold", "big"], 1),
    ("A1", "vocabulary", "", "A ___ teaches students at school.", ["doctor", "teacher", "driver"], 1),
    ("A1", "vocabulary", "", "You drink ___ when you are thirsty.", ["bread", "water", "rice"], 1),
    ("A1", "reading",
     "Sara gets up at seven. She eats breakfast and goes to school by bus.",
     "How does Sara go to school?", ["By car", "By bus", "On foot"], 1),
    ("A1", "reading",
     "Omar has a small cat. The cat is white and black. It likes milk.",
     "What does the cat like?", ["Milk", "Bread", "Fish"], 0),
    ("A1", "reading",
     "Today is Saturday. Ali does not go to work. He plays with his children in the park.",
     "Where is Ali today?", ["At work", "In the park", "At school"], 1),

    # ----------------------------- A2 ----------------------------------- #
    ("A2", "grammar", "", "Yesterday I ___ to the market.", ["go", "went", "gone"], 1),
    ("A2", "grammar", "", "She is ___ than her sister.", ["tall", "taller", "tallest"], 1),
    ("A2", "grammar", "", "We ___ watching TV when you called.", ["was", "were", "are"], 1),
    ("A2", "grammar", "", "I'm going ___ a new phone next week.", ["buy", "to buy", "bought"], 1),
    ("A2", "grammar", "", "There isn't ___ milk in the fridge.", ["some", "any", "no"], 1),
    ("A2", "grammar", "", "You ___ smoke here. It's forbidden.", ["mustn't", "don't have to", "might not"], 0),
    ("A2", "vocabulary", "", "The train leaves from platform two at the ___.", ["airport", "station", "harbour"], 1),
    ("A2", "vocabulary", "", "I was very ___ after the long trip, so I slept early.", ["tired", "excited", "hungry"], 0),
    ("A2", "vocabulary", "", "Can you ___ me your pen? I forgot mine.", ["borrow", "lend", "rent"], 1),
    ("A2", "vocabulary", "", "We booked a room with a beautiful ___ of the sea.", ["view", "look", "scene"], 0),
    ("A2", "reading",
     "Leila moved to a new city last month. At first she felt lonely, but then she joined a sports club and made new friends quickly.",
     "How did Leila make friends?", ["At work", "By joining a club", "At school"], 1),
    ("A2", "reading",
     "The museum is open every day except Monday. Tickets cost 50 dirhams, but students pay half price with a student card.",
     "How much do students pay?", ["50 dirhams", "25 dirhams", "Nothing"], 1),
    ("A2", "reading",
     "Karim wanted to cook dinner, but the fridge was empty. He wrote a shopping list and went to the supermarket before it closed.",
     "Why did Karim go to the supermarket?", ["The fridge was empty", "He was bored", "To meet a friend"], 0),

    # ----------------------------- B1 ----------------------------------- #
    ("B1", "grammar", "", "I have lived here ___ 2015.", ["since", "for", "from"], 0),
    ("B1", "grammar", "", "If it rains tomorrow, we ___ at home.", ["stay", "will stay", "stayed"], 1),
    ("B1", "grammar", "", "The report ___ by the manager yesterday.", ["signed", "was signed", "has signed"], 1),
    ("B1", "grammar", "", "She asked me where ___.", ["do I live", "I lived", "did I live"], 1),
    ("B1", "grammar", "", "You'd better ___ a jacket; it's cold outside.", ["taking", "take", "to take"], 1),
    ("B1", "grammar", "", "I'm not used ___ up so early.", ["to get", "to getting", "getting"], 1),
    ("B1", "vocabulary", "", "The company decided to ___ the meeting until next week.", ["postpone", "prevent", "propose"], 0),
    ("B1", "vocabulary", "", "It took her months to ___ from the operation.", ["recover", "remind", "repair"], 0),
    ("B1", "vocabulary", "", "This job offers a great ___ to travel abroad.", ["occasion", "opportunity", "possibility"], 1),
    ("B1", "vocabulary", "", "He couldn't ___ the noise any longer and left the cafe.", ["stand", "hold", "carry"], 0),
    ("B1", "reading",
     "Working from home has become common in many countries. Supporters say it saves commuting time and improves family life. Critics, however, argue that employees miss the social side of the office and can find it harder to separate work from rest.",
     "According to critics, what is a problem with working from home?",
     ["It costs companies more", "It is hard to separate work and rest", "It increases commuting time"], 1),
    ("B1", "reading",
     "The old library in the city centre will close next year, not because people have stopped reading, but because the building itself is no longer safe. The city plans to move the collection to a modern space near the university.",
     "Why will the library close?", ["People stopped reading", "The building is unsafe", "The university bought it"], 1),
    ("B1", "reading",
     "Amina started a small online shop selling handmade soap. She expected a few orders from friends, but after a video of her workshop spread on social media, she received hundreds of orders in one week.",
     "What changed Amina's business?", ["A newspaper article", "A social media video", "A new shop location"], 1),

    # ----------------------------- B2 ----------------------------------- #
    ("B2", "grammar", "", "If I ___ about the traffic, I would have left earlier.", ["knew", "had known", "know"], 1),
    ("B2", "grammar", "", "By the time we arrived, the film ___.", ["already started", "had already started", "has already started"], 1),
    ("B2", "grammar", "", "He denied ___ the window.", ["to break", "breaking", "break"], 1),
    ("B2", "grammar", "", "___ the bad weather, the match went ahead.", ["Despite", "Although", "However"], 0),
    ("B2", "grammar", "", "The proposal is said ___ rejected by the board.", ["to have been", "to be being", "having been"], 0),
    ("B2", "grammar", "", "No sooner ___ the house than it started to rain.", ["we had left", "had we left", "we left"], 1),
    ("B2", "vocabulary", "", "The two sides finally reached a ___ after months of negotiation.", ["compromise", "comparison", "component"], 0),
    ("B2", "vocabulary", "", "The evidence was too weak to ___ the theory.", ["substitute", "support", "surround"], 1),
    ("B2", "vocabulary", "", "Rising prices will inevitably ___ consumer behaviour.", ["affect", "effect", "afflict"], 0),
    ("B2", "vocabulary", "", "Her argument was so ___ that even her opponents applauded.", ["convincing", "convenient", "conventional"], 0),
    ("B2", "reading",
     "Urban farming projects have multiplied across the region in recent years. Beyond providing fresh produce, they turn neglected rooftops into green spaces and give neighbours a reason to cooperate. Yet most projects still depend on volunteers and short-term grants, raising doubts about their long-term viability.",
     "What concern does the passage raise about urban farming?",
     ["It produces low-quality food", "Its funding model may not last", "It damages rooftops"], 1),
    ("B2", "reading",
     "The novelist refused every interview for thirty years, insisting the books should speak for themselves. Ironically, this silence only fuelled public curiosity, and each rare public appearance became a media event in its own right.",
     "What effect did the novelist's silence have?",
     ["It reduced interest in the books", "It increased public curiosity", "It ended their career"], 1),
    ("B2", "reading",
     "While solar panels have dropped sharply in price, storage remains the bottleneck: without affordable batteries, surplus midday power is simply wasted, and grids must still rely on conventional plants after sunset.",
     "According to the passage, what is the main obstacle for solar energy?",
     ["Panel prices", "Battery storage costs", "Lack of sunlight"], 1),

    # ----------------------------- C1 ----------------------------------- #
    ("C1", "grammar", "", "Scarcely ___ the announcement when protests erupted.", ["the minister had made", "had the minister made", "the minister made"], 1),
    ("C1", "grammar", "", "___ his repeated assurances, few investors were convinced.", ["Notwithstanding", "Nevertheless", "Nonetheless"], 0),
    ("C1", "grammar", "", "The committee insisted that the report ___ published in full.", ["was", "be", "is"], 1),
    ("C1", "grammar", "", "Had it not been for the pilot's skill, the outcome ___ far worse.", ["would have been", "will be", "had been"], 0),
    ("C1", "grammar", "", "So intricate ___ that few economists fully grasp it.", ["the system is", "is the system", "the system being"], 1),
    ("C1", "vocabulary", "", "The senator's remarks were deliberately ___, allowing multiple interpretations.", ["ambiguous", "ambitious", "amicable"], 0),
    ("C1", "vocabulary", "", "Smartphones have become ___ in modern life; they are everywhere.", ["ubiquitous", "obsolete", "tenuous"], 0),
    ("C1", "vocabulary", "", "The new regulations are intended to ___ the risks of speculative trading.", ["mitigate", "aggravate", "instigate"], 0),
    ("C1", "vocabulary", "", "His account of events was entirely ___ with the official record.", ["at odds", "in line", "on par"], 0),
    ("C1", "reading",
     "The paradox of choice suggests that beyond a certain point, additional options do not liberate consumers but paralyse them. Faced with dozens of nearly identical products, shoppers often defer the decision entirely or, having chosen, are haunted by the suspicion that a better alternative was available. Some retailers have responded counterintuitively — by shrinking their ranges and reporting higher sales.",
     "What counterintuitive strategy have some retailers adopted?",
     ["Offering more choices", "Reducing their product ranges", "Raising their prices"], 1),
    ("C1", "reading",
     "Critics of standardized testing argue that it measures little beyond a student's aptitude for taking standardized tests. Defenders counter that, whatever its flaws, it remains the only instrument that permits comparison across wildly different schools — an imperfect ruler, they concede, but a ruler nonetheless.",
     "How do defenders of standardized testing characterize it?",
     ["As a flawless measure", "As an imperfect but useful comparison tool", "As unnecessary in modern schools"], 1),
    ("C1", "reading",
     "The restoration of the medina proceeded on the principle that authenticity is not frozen in time. Rather than reconstructing an idealized past, the architects retained later additions — colonial balconies, mid-century shopfronts — arguing that the city's layers, not any single era, constitute its true character.",
     "What principle guided the restoration?",
     ["Returning the medina to one original era", "Preserving the city's accumulated layers", "Removing all modern additions"], 1),
]
