# Generated by Django 5.0.6 on 2026-07-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='action',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
